// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq0i2rJV1a0853Cos6_XXZ-e6FY9dTcLo',
    appId: '1:673851034428:web:eececa8461a77891deec39',
    messagingSenderId: '673851034428',
    projectId: 'future-care-9ba85',
    authDomain: 'future-care-9ba85.firebaseapp.com',
    databaseURL: 'https://future-care-9ba85-default-rtdb.firebaseio.com',
    storageBucket: 'future-care-9ba85.appspot.com',
    measurementId: 'G-74X2VFB7SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_pGh-vKWE2RJHaAWF6IdlRhtyVNtqbg',
    appId: '1:673851034428:android:d22f1f93defdd4a6deec39',
    messagingSenderId: '673851034428',
    projectId: 'future-care-9ba85',
    databaseURL: 'https://future-care-9ba85-default-rtdb.firebaseio.com',
    storageBucket: 'future-care-9ba85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUW6XD-aD9EZplht1D-YZS56-PAbYWwtw',
    appId: '1:673851034428:ios:9a1aa5ed061285dbdeec39',
    messagingSenderId: '673851034428',
    projectId: 'future-care-9ba85',
    databaseURL: 'https://future-care-9ba85-default-rtdb.firebaseio.com',
    storageBucket: 'future-care-9ba85.appspot.com',
    iosBundleId: 'com.mypuffinfuturecare.app',
  );
}
